# Generated by Django 5.0 on 2024-01-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_selectmembershipplan_membershipplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
