# Generated by Django 5.0 on 2024-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_rename_traineedby_attendance_trainedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Reference',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
