# Generated by Django 5.0 on 2024-01-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_enrollment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Logout',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
